<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learn to become a graphic designer</title>
    <!-- CSS -->
    <link href="./resources/css/bootstrap.min.css" rel="stylesheet">
    <link href="./resources/css/main.css" rel="stylesheet">
    <link href="./resources/css/customs.css" rel="stylesheet">
</head>

<body>
    <header class="game-top">
        <div class="container text-center">
            <h1 class="header-title game-header py-5 mb-4">
                Game Design Today
            </h1>
        </div>
    </header>
    <div class="container">
        <div>
            <h3 class="mb-3"><span>Terms and Conditions</span></h3>
            <p class="mb-3"><span>Game Design Today Resources and its affiliates provide their services to you subject to the following conditions. If you visit, search, or shop at Game Design Today, you accept these conditions. Please read them carefully. In addition, when you use any current or future Game Design Today service or visit or purchase from any business affiliated with Game Design Today, whether included in the Game Design Today Resources website, you also will be subject to the guidelines and conditions applicable to that individual service or business.</span></p>
            <h3 class="mb-3"><span>Privacy</span></h3>
            <p class="mb-3"><span>Please review our Privacy Policy, which also governs your visit to Game Design Today.</span></p>
            <p class="mb-3"><span></span></p>
            <p class="mb-3"><span>Game Design Today Resources grants you a limited license to access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except with express written consent of Game Design Today. This license does not include any resale or commercial use of this site or its contents; any collection and use of any class or class provider listings, descriptions, or prices; any downloading or copying of account information for the benefit of another merchant; any derivative use of this site or its contents; or any use of robots, data mining, or similar data gathering and extraction tools. This site or any portion of this site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of Game Design Today. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including text, images page layout, or form) of Game Design Today and our affiliates without express written consent. You may not use any meta tags or any other "hidden text" utilizing the Game Design Today name or trademarks without the express written consent of Game Design Today. Any unauthorized use terminates the permission or license granted by Game Design Today Resources. You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the home page of Game Design Today so long as the link does not portray Game Design Today, its affiliates, or their classes, products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any Game Design Today or other proprietary graphic or trademark as part of the link without express written permission.<b style="mso-bidi-font-weight:normal"></b></span></p>
            <h3 class="mb-3"><span>Trademarks</span></h3>
            <p class="mb-3"><span>Game Design Today Resources and other marks indicated on our site are registered trademarks of Game Design Today and/or its parent companies and subsidiaries, in the United States and other countries. Game Design Today logos, graphics, button icons, page headers, service names, and scripts are trademarks or trade dress of Game Design Today and/or its parent companies and subsidiaries. Game Design Today trademarks and trade dress may not be used <span class="GramE">in connection with</span> any product or service that does not belong to Game Design Today, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Game Design Today. All other trademarks not owned by Game Design Today or its subsidiaries that appear on this site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Game Design Today or its subsidiaries.</span></p>
            <h3 class="mb-3">Copyright</h3>
            <p class="mb-3"><span>All content included on this site, such as graphics, logos, text, images, button icons, audio clips, digital downloads, data compilation, and software is the property of Game Design Today or its content suppliers and protected by United States and international copyright laws. The compilation of all content on this site is the exclusive property of Game Design Today and protected by U.S. and international copyright laws. All software used on this site is the property of Game Design Today or its software suppliers and protected by United States and international copyright laws.</span></p>
            <h3 class="mb-3"><span>Reviews, Comments, Communications, and Other</span></h3>
            <p class="mb-3"><span>Visitors may submit comments; send e-mail communications; and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, threatening, defamatory, obscene, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, commercial solicitation, political campaigning, mass mailings, chain letters, or any form of "spam." You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. Game Design Today reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content. Game Design Today has the right but not the obligation to oversee and edit or remove any activity or content. Game Design Today claims no responsibility and assumes no liability for any content posted by you or any third party.</span></p>
            <h3>Risk of Loss</h3>
            <p class="mb-3"><span>All classes or related items purchased from Game Design Today are made pursuant to either scheduled class dates or an individual retailer's shipment contract. This means that the risk of loss and title for such items pass to you upon the start of the class or delivery of purchased items through the mail carrier.</span></p>
            <h3 class="mb-3"><span>School Descriptions</span></h3>
            <p class="mb-3"><span>Game Design Today Game Design Today and its affiliates attempt to be as accurate as possible. However, Game Design Today does not warrant that descriptions or other content of this site are accurate, complete, reliable, current, or error-free. If a program offered by Game Design Today itself is not as described, your sole remedy is to contact the school.</span></p>
            <p class="mb-3"><span></span></p>
            <p class="mb-3"><span>Parties other than Game Design Today and its parent company and subsidiaries operate schools, stores, or sell product lines on this site. In addition, we provide links to the sites of affiliated companies and certain other businesses. We are not responsible for examining or evaluating, and we do not warrant the offerings of, any of these businesses or individuals or the content of their Web sites. Game Design Today does not assume any responsibility or liability for the actions, product, and content of all these and any other third parties. You should carefully review their privacy statements and other conditions of use. DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY THIS SITE IS PROVIDED BY Game Design Today ON AN "AS IS" AND "AS AVAILABLE" BASIS. Game Design Today MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS SITE OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THIS SITE. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS SITE IS AT YOUR SOLE RISK. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, Game Design Today DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A <span class="GramE">PARTICULAR PURPOSE</span>. Game Design Today Resources DOES NOT WARRANT THAT THIS SITE, ITS SERVERS, OR E-MAIL SENT FROM Game Design Today ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. Game Design Today Resources WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS SITE, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR <span class="GramE">ALL OF</span> THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.</span></p>
            <h3 class="mb-3"><span>Applicable Law</span></h3>
            <p class="mb-3"><span>By visiting Game Design Today, you agree that the laws of the state of California, without regard to principles of conflict of laws, will govern these User Terms and any dispute of any sort that might arise between you and Game Design Today or its affiliates.</span></p>
            <h3 class="mb-3"><span>Dispute Resolution; No Class Action</span></h3>
            <p class="mb-3"><span>Any matter and/or dispute relating in any way to your visit to or interaction with the Site, including compliance with these Terms, shall be submitted to binding confidential arbitration in California as provided in the Section titled â€œArbitrationâ€ (herein). Notwithstanding the foregoing, to the extent you have in any manner violated or threatened to violate our intellectual property rights, <span class="GramE">We</span> may seek injunctive or other appropriate relief in the state courts of the State of California and you consent to exclusive personal jurisdiction and venue in such courts. ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OR THE SITE MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED. ANY DISPUTE RESOLUTION PROCEEDINGS RELATING TO THESE TERMS OR THE SITE WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT AS A CLASS, CONSOLIDATED, JOINED OR REPRESENTATIVE ACTION AND THE PARTIES EXPRESSLY WAIVE ALL RIGHTS TO COMMENCE OR PARTICIPATE IN ANY CLASS, CONSOLIDATED OR REPRESENTATIVE ACTION/PROCEEDING. YOU AGREE THAT YOUR REVIEW OF THIS AGREEMENT TO ARBITRATE CLAIMS CONSTITUTES CONSIDERATION FOR SUCH WAIVER.</span></p>
        </div>
    </div>
    <?php include('components/footer.php'); ?>
</body>

</html>